/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.auth_gui;

import javax.swing.JOptionPane;

import com.buspass.auth.UserLoginSession;
import com.buspass.gui.PanelSwitcher;

/**
 *
 * @author USER
 */
public class LoginPanel extends javax.swing.JPanel {

    private PanelSwitcher appPanelSwitcher;
    private PanelSwitcher authPanelSwitcher;
    private UserLoginSession userLoginSession;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(UserLoginSession userLogin) {
        this.userLoginSession = userLogin;
        initComponents();
    }
    
    public void setAppPanelSwitcher(PanelSwitcher s) {
        this.appPanelSwitcher = s;
    }
    public void setAuthPanelSwitcher(PanelSwitcher s) {
        this.authPanelSwitcher = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        registerMessagePanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        loginFields = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        forgotPasswordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        userLoginLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        registerLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        registerLabel.setForeground(new java.awt.Color(0, 0, 255));
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        registerLabel.setText("Register Account");
        registerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerLabelMousePressed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        messageLabel.setText("New to Digital Bus Pass?");

        javax.swing.GroupLayout registerMessagePanelLayout = new javax.swing.GroupLayout(registerMessagePanel);
        registerMessagePanel.setLayout(registerMessagePanelLayout);
        registerMessagePanelLayout.setHorizontalGroup(
            registerMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerMessagePanelLayout.createSequentialGroup()
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        registerMessagePanelLayout.setVerticalGroup(
            registerMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usernameLabel.setText("Username");

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        passwordLabel.setText("Password");

        forgotPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        forgotPasswordLabel.setForeground(new java.awt.Color(0, 0, 255));
        forgotPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forgotPasswordLabel.setText("Forgot Password?");
        forgotPasswordLabel.setToolTipText("Click here to go to Password Reset Menu");
        forgotPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLabelMouseClicked(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        passwordField.addActionListener(this::passwordFieldActionPerformed);

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        javax.swing.GroupLayout loginFieldsLayout = new javax.swing.GroupLayout(loginFields);
        loginFields.setLayout(loginFieldsLayout);
        loginFieldsLayout.setHorizontalGroup(
            loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginFieldsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(loginFieldsLayout.createSequentialGroup()
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forgotPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        loginFieldsLayout.setVerticalGroup(
            loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFieldsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginFieldsLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(forgotPasswordLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginFieldsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userLoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLoginLabel.setText("LOGIN");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(userLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(userLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        add(centerPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String plainPassword = new String(passwordField.getPassword());
        
        // System.out.println();
        int result = userLoginSession.attemptLogin(username, plainPassword);
        
        switch(result) {
            case -1:
                showDialogUserNotFound();
                break;
                case 0:
                showDialogIncorrectPW();
                break;
                case 1:
                    showDialogLoginSuccess(username);

                    // System.out.println(userLoginSession.getUserId());
                    // System.out.println(userLoginSession.getFullName());
                    // System.out.println(userLoginSession.getAge());
                    // System.out.println(userLoginSession.getAddress());
                    // System.out.println(userLoginSession.getPhoneNumber());
                    // System.out.println(userLoginSession.getUserRoleId());

                    if (appPanelSwitcher != null) {
                        appPanelSwitcher.showPanel("main");
                    }
                    break;
            default:
                break;
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void forgotPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPasswordLabelMouseClicked

    private void registerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMouseClicked
        
    }//GEN-LAST:event_registerLabelMouseClicked

    private void registerLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLabelMousePressed
        if (authPanelSwitcher != null) {
            authPanelSwitcher.showPanel(AuthPanel.REGISTER);
        }
    }//GEN-LAST:event_registerLabelMousePressed

    private void showDialogUserNotFound() {
        JOptionPane.showMessageDialog(null, "User not found!", "Login Failed", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void showDialogIncorrectPW() {
        JOptionPane.showMessageDialog(null, "Incorrect Password!", "Login Failed", JOptionPane.INFORMATION_MESSAGE);
    }

    private void showDialogLoginSuccess(String username) {
        JOptionPane.showMessageDialog(null, "Login Successful with Username: " + username, "Login Successful", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel forgotPasswordLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginFields;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JPanel registerMessagePanel;
    private javax.swing.JLabel userLoginLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
