package com.buspass.gui.app_gui.dialogs;

import javax.swing.JOptionPane;
import javax.swing.JComboBox;

public class PaymentCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentCreatePanel
     */
    public PaymentCreatePanel() {
        initComponents();
        // Giả sử PaymentMethodID: 1: Cash, 2: Card, 3: Online Banking, 4: Free (Không hiển thị cho người dùng)
        paymentMethodComboBox.addItem("1: Cash");
        paymentMethodComboBox.addItem("2: Card");
        paymentMethodComboBox.addItem("3: Online Banking");
    }

    // --- Getters cho các trường dữ liệu ---
    public String getUserIdText() { return userIdField.getText().trim(); }
    public String getAmountText() { return amountField.getText().trim(); }

    
    // Lấy ID Phương thức thanh toán (chỉ lấy số đầu tiên)
    public Integer getPaymentMethodId() { 
        String selected = (String)paymentMethodComboBox.getSelectedItem();
        if (selected == null || selected.isEmpty()) return null;
        try {
            return Integer.parseInt(selected.split(":")[0]);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    public javax.swing.JButton getCreateButton() { return createButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        methodLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        userIdField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        paymentMethodComboBox = new javax.swing.JComboBox<>();
        optionPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("CREATE PAYMENT TRANSACTION");
        headerPanel.add(headerLabel);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setLayout(new java.awt.GridBagLayout());

        leftPanel.setLayout(new java.awt.GridLayout(3, 1));

        userIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userIdLabel.setText("User ID:");
        leftPanel.add(userIdLabel);

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountLabel.setText("Amount (VND):");
        leftPanel.add(amountLabel);

        methodLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        methodLabel.setText("Method:");
        leftPanel.add(methodLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        contentPanel.add(leftPanel, gridBagConstraints);

        rightPanel.setLayout(new java.awt.GridLayout(3, 1));

        userIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(userIdField);

        amountField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(amountField);

        paymentMethodComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(paymentMethodComboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 10);
        contentPanel.add(rightPanel, gridBagConstraints);

        add(contentPanel, java.awt.BorderLayout.CENTER);

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createButton.setText("CREATE");
        optionPanel.add(createButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        add(optionPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel methodLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JComboBox<String> paymentMethodComboBox;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField userIdField;
    private javax.swing.JLabel userIdLabel;
    // End of variables declaration//GEN-END:variables
}