package com.buspass.gui.app_gui.dialogs;

import java.util.Map;
import javax.swing.JOptionPane;

import com.buspass.queries.RouteQuery;
import static java.lang.Double.parseDouble;
import static java.lang.Float.parseFloat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class RouteCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final RouteQuery routeQuery;

    public RouteCreatePanel(RouteQuery routeQuery) {
        initComponents();
        this.routeQuery = routeQuery != null ? routeQuery : new RouteQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        routeNameLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        fareLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        routeNameField = new javax.swing.JTextField();
        startField = new javax.swing.JTextField();
        endField = new javax.swing.JTextField();
        fareField = new javax.swing.JTextField();
        distanceField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createButton.setText("CREATE");
        createButton.addActionListener(this::createButtonActionPerformed);
        optionPanel.add(createButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("CREATE ROUTE");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(6, 1));

        routeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeNameLabel.setText("RouteName");
        leftPanel.add(routeNameLabel);

        startLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLabel.setText("Start");
        leftPanel.add(startLabel);

        endLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endLabel.setText("End");
        leftPanel.add(endLabel);

        fareLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fareLabel.setText("Fare");
        leftPanel.add(fareLabel);

        distanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        distanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceLabel.setText("Distance");
        leftPanel.add(distanceLabel);

        durationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationLabel.setText("Duration");
        leftPanel.add(durationLabel);

        rightPanel.setLayout(new java.awt.GridLayout(6, 1));

        routeNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(routeNameField);

        startField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(startField);

        endField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(endField);

        fareField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(fareField);

        distanceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(distanceField);

        durationField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(durationField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        performInsert();
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField distanceField;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField endField;
    private javax.swing.JLabel endLabel;
    private javax.swing.JTextField fareField;
    private javax.swing.JLabel fareLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField routeNameField;
    private javax.swing.JLabel routeNameLabel;
    private javax.swing.JTextField startField;
    private javax.swing.JLabel startLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getCreateButton() { return createButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Route
    private String getRouteName() { return routeNameField.getText().trim(); }
    private String getStart() { return startField.getText().trim(); } // Updated to use JTextField
    private String getEnd() { return endField.getText().trim(); }
    private Double getFare() { return parseDouble(fareField.getText().trim()); }
    private Float getDistance() { return parseFloat(distanceField.getText().trim()); }
    private Integer getDuration() { return parseIntNullable(durationField.getText().trim()); }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void performInsert() {

        String routeName = getRouteName();
        String start = getStart();
        String end = getEnd();
        Double fare = getFare();
        Float distance = getDistance();
        Integer duration = getDuration();

        boolean ok;
        try {
            ok = routeQuery.registerRoute(routeName, start, end, fare, distance, duration);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Creation failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ok) 
            JOptionPane.showMessageDialog(this, "Creation failed.", "Error", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "New Route Created.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
}
