package com.buspass.gui.app_gui.dialogs;

import java.util.Map;
import javax.swing.JOptionPane;

import com.buspass.queries.RouteQuery;
import static java.lang.Double.parseDouble;
import static java.lang.Float.parseFloat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class RouteUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final RouteQuery routeQuery;
    private Map<String,Object> currentRoute; // cached fetched route row

    public RouteUpdatePanel(RouteQuery routeQuery) {
        initComponents();
        this.routeQuery = routeQuery != null ? routeQuery : new RouteQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        routeIdLabel = new javax.swing.JLabel();
        routeNameLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        fareLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        routeIdPanel = new javax.swing.JPanel();
        routeIdField = new javax.swing.JTextField();
        findIdButton = new javax.swing.JButton();
        routeNameField = new javax.swing.JTextField();
        startField = new javax.swing.JTextField();
        endField = new javax.swing.JTextField();
        fareField = new javax.swing.JTextField();
        distanceField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        optionPanel.add(updateButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("UPDATE ROUTE");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(8, 1));

        routeIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routeIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeIdLabel.setText("RouteID");
        leftPanel.add(routeIdLabel);

        routeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeNameLabel.setText("RouteName");
        leftPanel.add(routeNameLabel);

        startLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        startLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLabel.setText("Start");
        leftPanel.add(startLabel);

        endLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        endLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endLabel.setText("End");
        leftPanel.add(endLabel);

        fareLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fareLabel.setText("Fare");
        leftPanel.add(fareLabel);

        distanceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        distanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceLabel.setText("Distance");
        leftPanel.add(distanceLabel);

        durationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationLabel.setText("Duration");
        leftPanel.add(durationLabel);

        rightPanel.setLayout(new java.awt.GridLayout(8, 1));

        routeIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routeIdField.addActionListener(this::routeIdFieldActionPerformed);

        findIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findIdButton.setText("Find");
        findIdButton.addActionListener(this::findIdButtonActionPerformed);

        javax.swing.GroupLayout routeIdPanelLayout = new javax.swing.GroupLayout(routeIdPanel);
        routeIdPanel.setLayout(routeIdPanelLayout);
        routeIdPanelLayout.setHorizontalGroup(
            routeIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routeIdPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(routeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        routeIdPanelLayout.setVerticalGroup(
            routeIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routeIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(routeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanel.add(routeIdPanel);

        routeNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(routeNameField);

        startField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(startField);

        endField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(endField);

        fareField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(fareField);

        distanceField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(distanceField);

        durationField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(durationField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void routeIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeIdFieldActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        fetchRoute();
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        performUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField distanceField;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField endField;
    private javax.swing.JLabel endLabel;
    private javax.swing.JTextField fareField;
    private javax.swing.JLabel fareLabel;
    private javax.swing.JButton findIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField routeIdField;
    private javax.swing.JLabel routeIdLabel;
    private javax.swing.JPanel routeIdPanel;
    private javax.swing.JTextField routeNameField;
    private javax.swing.JLabel routeNameLabel;
    private javax.swing.JTextField startField;
    private javax.swing.JLabel startLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getUpdateButton() { return updateButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }
    public javax.swing.JButton getFindRouteButton() { return findIdButton; }

    // Field getters specific to Route
    private int getRouteId() { return parseInt(routeIdField.getText().trim(), -1); }
    private String getRouteName() { return routeNameField.getText().trim(); }
    private String getStart() { return startField.getText().trim(); } // Updated to use JTextField
    private String getEnd() { return endField.getText().trim(); }
    private Double getFare() { return parseDouble(fareField.getText().trim()); }
    private Float getDistance() { return parseFloat(distanceField.getText().trim()); }
    private Integer getDuration() {return parseIntNullable(durationField.getText().trim()); }

    private int parseInt(String s, int fallback) { 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return fallback; 
        } 
    }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void setRouteFields(Map<String,Object> route) {
        routeNameField.setText(asString(route.get("RouteName")));
        startField.setText(asString(route.get("Start")));
        endField.setText(asString(route.get("End")));
        fareField.setText(asString(route.get(""), asString(route.get("Fare"))));
        distanceField.setText(asString(route.get("distance")));
        durationField.setText(asString(route.get("duration")));        
    }
    
    private String asString(Object o) { return o==null?"":o.toString(); }
    private String asString(Object primary, String alt) { return primary!=null?primary.toString(): (alt==null?"":alt); }

    private void fetchRoute() {
        int routeId = getRouteId();
        if (routeId <= 0) { 
            JOptionPane.showMessageDialog(this, "Enter a valid RouteID.", "Input", JOptionPane.WARNING_MESSAGE); 
            return; 
        }
        currentRoute = routeQuery.getRouteById(routeId);

        if (currentRoute == null) { 
            JOptionPane.showMessageDialog(this, "Route not found.", "Not Found", JOptionPane.INFORMATION_MESSAGE); 
            return; 
        }
        setRouteFields(currentRoute);
    }

    private void performUpdate() {
        int routeId = getRouteId();
        if (routeId <= 0) { JOptionPane.showMessageDialog(this, "Provide RouteID first.", "Validation", JOptionPane.WARNING_MESSAGE); return; }
        if (currentRoute == null) currentRoute = routeQuery.getRouteById(routeId);
        if (currentRoute == null) { JOptionPane.showMessageDialog(this, "Fetch route before updating.", "Validation", JOptionPane.WARNING_MESSAGE); return; }

        String newRouteName = getRouteName();
        String newStart = getStart();
        String newEnd = getEnd();
        Double newFare = getFare();
        Float newDistance = getDistance();
        Integer newDuration = getDuration();

        StringBuilder summary = new StringBuilder();
        boolean anyChange = false;
        try {
            if (!newRouteName.isEmpty() && !newRouteName.equals(asString(currentRoute.get("RouteName")))) {
                if (routeQuery.updateRouteName(routeId, newRouteName)) { summary.append("Route Name updated.\n"); anyChange = true; }
            }
            if (newStart != null && !asString(currentRoute.get("Start")).equals(String.valueOf(newStart))) {
                if (routeQuery.updateStartLocation(routeId, newStart)) { summary.append("Start Location updated.\n"); anyChange = true; }
            }
            if (newEnd != null && !asString(currentRoute.get("End")).equals(String.valueOf(newEnd))) {
                if (routeQuery.updateEndLocation(routeId, newEnd)) { summary.append("End Location updated.\n"); anyChange = true; }
            }
            if (newFare != null && !asString(currentRoute.get("Fare")).equals(String.valueOf(newFare))) {
                if (routeQuery.updateFare(routeId, newFare)) { summary.append("Fare updated.\n"); anyChange = true; }
            }
            if (newDistance != null && !asString(currentRoute.get("Distance")).equals(String.valueOf(newDistance))) {
                if (routeQuery.updateDistance(routeId, newDistance)) { summary.append("Distance updated.\n"); anyChange = true; }
            }
            if (newDuration != null && !asString(currentRoute.get("Duration")).equals(String.valueOf(newDuration))) {
                if (routeQuery.updateDuration(routeId, newDuration)) { summary.append("Duration updated.\n"); anyChange = true; }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (anyChange) {
            JOptionPane.showMessageDialog(this, summary.toString(), "Update Success", JOptionPane.INFORMATION_MESSAGE);
            currentRoute = routeQuery.getRouteById(routeId); // refresh cache
            setRouteFields(currentRoute);
        } else {
            JOptionPane.showMessageDialog(this, "No changes applied.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
