package com.buspass.gui.app_gui.dialogs;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.NumberFormatter;

import com.buspass.queries.TripQuery;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class TripCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final TripQuery tripQuery;

    public TripCreatePanel(TripQuery tripQuery) {
        numberFormatter.setAllowsInvalid(false); // Disallow invalid edits
        numberFormatter.setCommitsOnValidEdit(true);

        initComponents();
        this.tripQuery = tripQuery != null ? tripQuery : new TripQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        tripDateLabel = new javax.swing.JLabel();
        departureLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        busIdLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        tripDateField = new javax.swing.JFormattedTextField(df);
        departureField = new javax.swing.JFormattedTextField(tf);
        arrivalField = new javax.swing.JFormattedTextField(tf);
        busIdField = new javax.swing.JFormattedTextField(numberFormatter);

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createButton.setText("CREATE");
        createButton.addActionListener(this::createButtonActionPerformed);
        optionPanel.add(createButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("CREATE TRIP");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(6, 1));

        tripDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tripDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripDateLabel.setText("Trip Date");
        leftPanel.add(tripDateLabel);

        departureLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departureLabel.setText("Departure Time");
        leftPanel.add(departureLabel);

        arrivalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        arrivalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrivalLabel.setText("Arrival Time");
        leftPanel.add(arrivalLabel);

        busIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busIdLabel.setText("Bus ID");
        leftPanel.add(busIdLabel);

        rightPanel.setLayout(new java.awt.GridLayout(6, 1));

        tripDateField.addActionListener(this::tripDateFieldActionPerformed);
        rightPanel.add(tripDateField);

        departureField.addActionListener(this::departureFieldActionPerformed);
        rightPanel.add(departureField);

        arrivalField.addActionListener(this::arrivalFieldActionPerformed);
        rightPanel.add(arrivalField);

        busIdField.addActionListener(this::busIdFieldActionPerformed);
        rightPanel.add(busIdField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        performInsert();
    }//GEN-LAST:event_createButtonActionPerformed

    private void tripDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripDateFieldActionPerformed

    private void departureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureFieldActionPerformed

    private void arrivalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalFieldActionPerformed

    private void busIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busIdFieldActionPerformed

    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tf = new SimpleDateFormat("HH:mm:ss");
    // Create a formatter that only allows integers
    NumberFormat integerFormat = NumberFormat.getIntegerInstance();
    NumberFormatter numberFormatter = new NumberFormatter(integerFormat);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField arrivalField;
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JFormattedTextField busIdField;
    private javax.swing.JLabel busIdLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JFormattedTextField departureField;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JFormattedTextField tripDateField;
    private javax.swing.JLabel tripDateLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getCreateButton() { return createButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Bus
    private String getTripDate() { return tripDateField.getText().trim(); }
    private String getDepartureTime() { return departureField.getText().trim(); }
    private String getArrivalTime() { return arrivalField.getText().trim(); }
    private Integer getBusId() { return parseIntNullable(busIdField.getText().trim()); }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void performInsert() {

        String tripDate = getTripDate();
        String departureTime = getDepartureTime();
        String arrivalTime = getArrivalTime();
        Integer busId = getBusId();

        boolean ok = true;
        try {
            ok = tripQuery.createTrip(tripDate, departureTime, arrivalTime, busId);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Trip Creation failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ok) 
            JOptionPane.showMessageDialog(this, "Trip Creation failed.", "Error", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "New Trip Record Created.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
}
