package com.buspass.gui.app_gui.dialogs;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.text.NumberFormatter;

import com.buspass.queries.TripQuery;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class TripUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final TripQuery tripQuery;
    private Map<String,Object> currentTrip;

    public TripUpdatePanel(TripQuery tripQuery) {
        integerFormat.setGroupingUsed(false); // no commas
        numberFormatter.setAllowsInvalid(false); // Disallow invalid edits
        numberFormatter.setCommitsOnValidEdit(true);

        initComponents();
        this.tripQuery = tripQuery != null ? tripQuery : new TripQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        tripIdLabel = new javax.swing.JLabel();
        tripDateLabel = new javax.swing.JLabel();
        departureLabel = new javax.swing.JLabel();
        arrivalLabel = new javax.swing.JLabel();
        busIdLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        driverIdPanel = new javax.swing.JPanel();
        tripIdField = new javax.swing.JFormattedTextField(numberFormatter);
        findIdButton = new javax.swing.JButton();
        tripDateField = new javax.swing.JFormattedTextField(df);
        departureField = new javax.swing.JFormattedTextField(tf);
        arrivalField = new javax.swing.JFormattedTextField(tf);
        busIdField = new javax.swing.JFormattedTextField(numberFormatter);

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        updateButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        optionPanel.add(updateButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("UPDATE TRIP");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(6, 1));

        tripIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tripIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripIdLabel.setText("Trip ID");
        leftPanel.add(tripIdLabel);

        tripDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tripDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripDateLabel.setText("Trip Date");
        leftPanel.add(tripDateLabel);

        departureLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departureLabel.setText("Departure Time");
        leftPanel.add(departureLabel);

        arrivalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        arrivalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrivalLabel.setText("Arrival Time");
        leftPanel.add(arrivalLabel);

        busIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busIdLabel.setText("Bus ID");
        leftPanel.add(busIdLabel);

        rightPanel.setLayout(new java.awt.GridLayout(6, 1));

        tripIdField.setMaximumSize(new java.awt.Dimension(64, 26));
        tripIdField.setName(""); // NOI18N
        tripIdField.addActionListener(this::tripIdFieldActionPerformed);

        findIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findIdButton.setText("Find");
        findIdButton.addActionListener(this::findIdButtonActionPerformed);

        javax.swing.GroupLayout driverIdPanelLayout = new javax.swing.GroupLayout(driverIdPanel);
        driverIdPanel.setLayout(driverIdPanelLayout);
        driverIdPanelLayout.setHorizontalGroup(
            driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverIdPanelLayout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(driverIdPanelLayout.createSequentialGroup()
                    .addComponent(tripIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 89, Short.MAX_VALUE)))
        );
        driverIdPanelLayout.setVerticalGroup(
            driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(findIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tripIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        rightPanel.add(driverIdPanel);

        tripDateField.addActionListener(this::tripDateFieldActionPerformed);
        rightPanel.add(tripDateField);

        departureField.addActionListener(this::departureFieldActionPerformed);
        rightPanel.add(departureField);

        arrivalField.addActionListener(this::arrivalFieldActionPerformed);
        rightPanel.add(arrivalField);

        busIdField.addActionListener(this::busIdFieldActionPerformed);
        rightPanel.add(busIdField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        performUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void tripDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripDateFieldActionPerformed

    private void departureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureFieldActionPerformed

    private void arrivalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalFieldActionPerformed

    private void busIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busIdFieldActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        fetchTrip();
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void tripIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripIdFieldActionPerformed

    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tf = new SimpleDateFormat("HH:mm:ss");
    // Create a formatter that only allows integers
    NumberFormat integerFormat = NumberFormat.getIntegerInstance();
    NumberFormatter numberFormatter = new NumberFormatter(integerFormat);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField arrivalField;
    private javax.swing.JLabel arrivalLabel;
    private javax.swing.JFormattedTextField busIdField;
    private javax.swing.JLabel busIdLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JFormattedTextField departureField;
    private javax.swing.JLabel departureLabel;
    private javax.swing.JPanel driverIdPanel;
    private javax.swing.JButton findIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JFormattedTextField tripDateField;
    private javax.swing.JLabel tripDateLabel;
    private javax.swing.JFormattedTextField tripIdField;
    private javax.swing.JLabel tripIdLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getCreateButton() { return updateButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Bus
    private Integer getTripId() { return parseIntNullable(tripIdField.getText().trim()); }
    private String getTripDate() { return tripDateField.getText().trim(); }
    private String getDepartureTime() { return departureField.getText().trim(); }
    private String getArrivalTime() { return arrivalField.getText().trim(); }
    private Integer getBusId() { return parseIntNullable(busIdField.getText().trim()); }

    public void setTripDate(String tripDate) { tripDateField.setText(tripDate);} 
    public void setDepartureTime(String departureTime) { departureField.setText(departureTime);}
    public void setArrivalTime(String arrivalTime) { arrivalField.setText(arrivalTime);} 
    public void setBusId(String busId) { busIdField.setText(busId); }    

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }
    
    private String asString(Object o) { return o==null?"":o.toString(); }
    private boolean isBlank(String s) { return s==null || s.trim().isEmpty(); }

    private void setTripFields(Map<String,Object> trip) {
        setTripDate(asString(trip.get("TripDate")));
        setDepartureTime(asString(trip.get("DepartureTime")));
        setArrivalTime(asString(trip.get("ArrivalTime")));
        setBusId(asString(trip.get("BusID")));
    }

    private void fetchTrip() {
        Integer tripId = getTripId();
        if (tripId == null || tripId <= 0) { 
            JOptionPane.showMessageDialog(this, "Enter a valid TripID.", "Input", JOptionPane.WARNING_MESSAGE); 
            return; 
        }
        currentTrip = tripQuery.getTripById(tripId);
        if (currentTrip == null) { 
            JOptionPane.showMessageDialog(this, "Trip not found.", "Not Found", JOptionPane.INFORMATION_MESSAGE); 
            return; 
        }
        setTripFields(currentTrip);
    }

    private void performUpdate() {
        Integer tripId = getTripId();
        if (tripId == null || tripId <= 0) { 
            JOptionPane.showMessageDialog(this, "Provide TripID first.", "Validation", JOptionPane.WARNING_MESSAGE); return; 
        }
        if (currentTrip == null) currentTrip = tripQuery.getTripById(tripId);
        if (currentTrip == null) { 
            JOptionPane.showMessageDialog(this, "Fetch trip before updating.", "Validation", JOptionPane.WARNING_MESSAGE); return; 
        }

        String newDate = getTripDate();
        String newDep = getDepartureTime();
        String newArr = getArrivalTime();
        Integer newBusId = getBusId();

        StringBuilder summary = new StringBuilder();
        boolean anyChange = false;
        try {
            if (!isBlank(newDate) && !newDate.equals(asString(currentTrip.get("TripDate")))) {
                if (tripQuery.updateTripDate(tripId, newDate)) { 
                    summary.append("TripDate updated.\n"); 
                    anyChange = true;
                }
            }
            if (!isBlank(newDep) && !isBlank(newArr) && (!newDep.equals(asString(currentTrip.get("DepartureTime"))) || !newArr.equals(asString(currentTrip.get("ArrivalTime"))))) {
                if (tripQuery.updateTimes(tripId, newDep, newArr)) { 
                    summary.append("Times updated.\n"); 
                    anyChange = true; 
                }
            }
            if (newBusId != null && !String.valueOf(newBusId).equals(asString(currentTrip.get("BusID")))) {
                if (tripQuery.updateBusId(tripId, newBusId)) { 
                    summary.append("BusID updated.\n"); 
                    anyChange = true; 
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (anyChange) {
            JOptionPane.showMessageDialog(this, summary.toString(), "Update Success", JOptionPane.INFORMATION_MESSAGE);
            currentTrip = tripQuery.getTripById(tripId); // refresh cache
            setTripFields(currentTrip);
        } else {
            JOptionPane.showMessageDialog(this, "No changes applied.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
