/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;

import com.buspass.gui.app_gui.dialogs.BusCreatePanel;
import com.buspass.gui.app_gui.dialogs.BusUpdatePanel;
import com.buspass.queries.BusQuery;

/**
 *
 * @author USER
 */
public class BusesPanel extends javax.swing.JPanel implements InMiddlePanel {

    /**
     * Creates new form UsersPanel
     */
    public BusesPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private BusQuery busQuery = new BusQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getBusByIdButton = new javax.swing.JButton();
        getAllBusesButton = new javax.swing.JButton();
        getTripsWithBusButton = new javax.swing.JButton();
        createBusButton = new javax.swing.JButton();
        updateBusButton = new javax.swing.JButton();
        deleteBusButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getBusByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getBusByIdButton.setText("Get Bus By ID");
        getBusByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getBusByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.addActionListener(this::getBusByIdButtonActionPerformed);
        buttonPanel.add(getBusByIdButton);

        getAllBusesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllBusesButton.setText("Get All Buses");
        getAllBusesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllBusesButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.addActionListener(this::getAllBusesButtonActionPerformed);
        buttonPanel.add(getAllBusesButton);

        getTripsWithBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTripsWithBusButton.setText("Get Trips with Bus");
        getTripsWithBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTripsWithBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.addActionListener(this::getTripsWithBusButtonActionPerformed);
        buttonPanel.add(getTripsWithBusButton);

        createBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createBusButton.setText("Create Bus");
        createBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createBusButton.addActionListener(this::createBusButtonActionPerformed);
        buttonPanel.add(createBusButton);

        updateBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBusButton.setText("Update Bus");
        updateBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateBusButton.addActionListener(this::updateBusButtonActionPerformed);
        buttonPanel.add(updateBusButton);

        deleteBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBusButton.setText("Delete Bus");
        deleteBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteBusButton.addActionListener(this::deleteBusButtonActionPerformed);
        buttonPanel.add(deleteBusButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("BUSES");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateBusButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Update Bus",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        BusUpdatePanel panel = new BusUpdatePanel(busQuery);
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());

        dialog.setVisible(true); // blocks until closed
    }// GEN-LAST:event_updateBusButtonActionPerformed

    private void getBusByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getBusByIdButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter BusID:", "Find Bus",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "BusID cannot be empty.", "Input error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int busId;
        try {
            busId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric BusID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> bus = busQuery.getBusInfoById(busId);
            if (bus == null || bus.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No bus found with ID: " + busId, "Not found",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }
            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(bus);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching bus: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_getBusByIdButtonActionPerformed

    private void getAllBusesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getAllBusesButtonActionPerformed
        middlePanel.setTableContents(resultTable, busQuery.getAllBuses());
    }// GEN-LAST:event_getAllBusesButtonActionPerformed

    private void getTripsWithBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getTripsWithBusButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter BusID to list its trips:", "Bus Trips",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "BusID cannot be empty.", "Input error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int busId;
        try {
            busId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric BusID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            middlePanel.setTableContents(resultTable, busQuery.getTripsTraveledById(busId));
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching trips: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_getTripsWithBusButtonActionPerformed

    private void createBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createBusButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Create Bus",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        BusCreatePanel panel = new BusCreatePanel(busQuery);
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getCreateButton().addActionListener(e -> dialog.dispose());

        dialog.setVisible(true); // blocks until closed
    }// GEN-LAST:event_createBusButtonActionPerformed

    private void deleteBusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBusButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter BusID to delete:", "Delete Bus",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "BusID cannot be empty.", "Input error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int busId;
        try {
            busId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid BusID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete BusID " + busId + "?", "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION)
            return;
        try {
            boolean ok = busQuery.removeBus(busId);
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Bus deleted.", "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                middlePanel.setTableContents(resultTable, busQuery.getAllBuses());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Bus not found or could not be deleted.", "Failure",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting bus: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_deleteBusButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createBusButton;
    private javax.swing.JButton deleteBusButton;
    private javax.swing.JButton getAllBusesButton;
    private javax.swing.JButton getBusByIdButton;
    private javax.swing.JButton getTripsWithBusButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateBusButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        createBusButton.setVisible(false);
        deleteBusButton.setVisible(false);
        updateBusButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        createBusButton.setVisible(true);
        deleteBusButton.setVisible(true);
        updateBusButton.setVisible(true);
    }
}
