/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;

import com.buspass.auth.UserLoginSession;
import com.buspass.queries.PaymentQuery;

/**
 *
 * @author USER
 */
public class PaymentsPanel extends javax.swing.JPanel implements InMiddlePanel {

    /**
     * Creates new form UsersPanel
     */
    public PaymentsPanel(UserLoginSession userLoginSession) {
        initComponents();
        this.userLoginSession = userLoginSession;
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private PaymentQuery paymentQuery = new PaymentQuery();
    private UserLoginSession userLoginSession;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        myPaymentsButton = new javax.swing.JButton();
        getPaymentsOfUserButton = new javax.swing.JButton();
        createTransactionButton = new javax.swing.JButton();
        deletePaymentButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        myPaymentsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myPaymentsButton.setText("My Payments");
        myPaymentsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        myPaymentsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.addActionListener(this::myPaymentsButtonActionPerformed);
        buttonPanel.add(myPaymentsButton);

        getPaymentsOfUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getPaymentsOfUserButton.setText("Get Payments Of User");
        getPaymentsOfUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getPaymentsOfUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.addActionListener(this::getPaymentsOfUserButtonActionPerformed);
        buttonPanel.add(getPaymentsOfUserButton);

        createTransactionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createTransactionButton.setText("Create Transaction");
        createTransactionButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createTransactionButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createTransactionButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createTransactionButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createTransactionButton.addActionListener(this::createTransactionButtonActionPerformed);
        buttonPanel.add(createTransactionButton);

        deletePaymentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletePaymentButton.setText("Delete Payment");
        deletePaymentButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deletePaymentButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.addActionListener(this::deletePaymentButtonActionPerformed);
        buttonPanel.add(deletePaymentButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("PAYMENTS");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myPaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_myPaymentsButtonActionPerformed
        if (userLoginSession.getUserId() == null) return;

        int userId = userLoginSession.getUserId();
        try {
            middlePanel.setTableContents(resultTable, paymentQuery.getPaymentsByUserId(userId));
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching payments: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_myPaymentsButtonActionPerformed

    private void getPaymentsOfUserButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getPaymentsOfUserButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter UserID to list payments:",
                "Payments Of User", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "UserID required.", "Input",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int userId;
        try {
            userId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid UserID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            middlePanel.setTableContents(resultTable, paymentQuery.getPaymentsByUserId(userId));
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching payments: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_getPaymentsOfUserButtonActionPerformed

    private void createTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createTransactionButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_createTransactionButtonActionPerformed

    private void deletePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deletePaymentButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter PaymentID to delete:", "Delete Payment",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "PaymentID required.", "Input",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int paymentId;
        try {
            paymentId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid PaymentID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete PaymentID " + paymentId + "?", "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION)
            return;
        try {
            boolean ok = paymentQuery.deletePayment(paymentId);
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Payment deleted.", "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Payment not found or failed to delete.", "Failure",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting payment: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_deletePaymentButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createTransactionButton;
    private javax.swing.JButton deletePaymentButton;
    private javax.swing.JButton getPaymentsOfUserButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton myPaymentsButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        createTransactionButton.setVisible(false);
        deletePaymentButton.setVisible(false);
        getPaymentsOfUserButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        createTransactionButton.setVisible(true);
        deletePaymentButton.setVisible(true);
        getPaymentsOfUserButton.setVisible(false);
    }
}
