/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;

import com.buspass.queries.RouteQuery;

/**
 *
 * @author USER
 */
public class RoutesPanel extends javax.swing.JPanel implements InMiddlePanel {

    /**
     * Creates new form UsersPanel
     */
    public RoutesPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private RouteQuery routeQuery = new RouteQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getRouteByIdButton = new javax.swing.JButton();
        getAllRoutesButton = new javax.swing.JButton();
        createRouteButton = new javax.swing.JButton();
        updateRouteButton = new javax.swing.JButton();
        deleteRouteButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getRouteByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getRouteByIdButton.setText("Get Route By ID");
        getRouteByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getRouteByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getRouteByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getRouteByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getRouteByIdButton.addActionListener(this::getRouteByIdButtonActionPerformed);
        buttonPanel.add(getRouteByIdButton);

        getAllRoutesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllRoutesButton.setText("Get All Routes");
        getAllRoutesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllRoutesButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllRoutesButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllRoutesButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllRoutesButton.addActionListener(this::getAllRoutesButtonActionPerformed);
        buttonPanel.add(getAllRoutesButton);

        createRouteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createRouteButton.setText("Create Route");
        createRouteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createRouteButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createRouteButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createRouteButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createRouteButton.addActionListener(this::createRouteButtonActionPerformed);
        buttonPanel.add(createRouteButton);

        updateRouteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateRouteButton.setText("Update Route");
        updateRouteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateRouteButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateRouteButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateRouteButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateRouteButton.addActionListener(this::updateRouteButtonActionPerformed);
        buttonPanel.add(updateRouteButton);

        deleteRouteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteRouteButton.setText("Delete Route");
        deleteRouteButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteRouteButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteRouteButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteRouteButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteRouteButton.addActionListener(this::deleteRouteButtonActionPerformed);
        buttonPanel.add(deleteRouteButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("ROUTES");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateRouteButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_updateRouteButtonActionPerformed

    private void getRouteByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getRouteByIdButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter RouteID:", "Find Route",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "RouteID cannot be empty.", "Input error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int routeId;
        try {
            routeId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric RouteID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> route = routeQuery.getRouteById(routeId);
            if (route == null || route.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No route found with ID: " + routeId, "Not found",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }
            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(route);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching route: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_getRouteByIdButtonActionPerformed

    private void getAllRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getAllRoutesButtonActionPerformed
        middlePanel.setTableContents(resultTable, routeQuery.getAllRoutes());
    }// GEN-LAST:event_getAllRoutesButtonActionPerformed

    private void createRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createRouteButtonActionPerformed
        
    }// GEN-LAST:event_createRouteButtonActionPerformed

    private void deleteRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteRouteButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter RouteID to delete:", "Delete Route",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "RouteID required.", "Input",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int routeId;
        try {
            routeId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid RouteID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete RouteID " + routeId + "?", "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION)
            return;
        try {
            boolean ok = routeQuery.removeRoute(routeId);
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Route deleted.", "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                middlePanel.setTableContents(resultTable, routeQuery.getAllRoutes());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Route not found or failed to delete.", "Failure",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_deleteRouteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createRouteButton;
    private javax.swing.JButton deleteRouteButton;
    private javax.swing.JButton getAllRoutesButton;
    private javax.swing.JButton getRouteByIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateRouteButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        createRouteButton.setVisible(false);
        deleteRouteButton.setVisible(false);
        updateRouteButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        createRouteButton.setVisible(true);
        deleteRouteButton.setVisible(true);
        updateRouteButton.setVisible(true);
    }
}
