/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;

import java.util.Map;

import com.buspass.auth.UserLoginSession;
import com.buspass.queries.TicketQuery;

/**
 *
 * @author USER
 */
public class TicketsPanel extends javax.swing.JPanel implements InMiddlePanel{

    
    private UserLoginSession userLoginSession;
    private MiddlePanel middlePanel = new MiddlePanel();
    private TicketQuery ticketQuery = new TicketQuery();
    
    /**
     * Creates new form UsersPanel
     */
    public TicketsPanel(UserLoginSession userLoginSession) {
        initComponents();
        this.userLoginSession = userLoginSession;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        buyTicketButton = new javax.swing.JButton();
        myTicketsButton = new javax.swing.JButton();
        changeToTripButton = new javax.swing.JButton();
        getTicketsOfUserButton = new javax.swing.JButton();
        deleteTicketButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        buyTicketButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buyTicketButton.setText("Buy Ticket");
        buyTicketButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buyTicketButton.setMaximumSize(new java.awt.Dimension(180, 40));
        buyTicketButton.setMinimumSize(new java.awt.Dimension(180, 40));
        buyTicketButton.setPreferredSize(new java.awt.Dimension(180, 40));
        buyTicketButton.addActionListener(this::buyTicketButtonActionPerformed);
        buttonPanel.add(buyTicketButton);

        myTicketsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myTicketsButton.setText("My Tickets");
        myTicketsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        myTicketsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        myTicketsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        myTicketsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        myTicketsButton.addActionListener(this::myTicketsButtonActionPerformed);
        buttonPanel.add(myTicketsButton);

        changeToTripButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeToTripButton.setText("Change Ticket Trip");
        changeToTripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        changeToTripButton.setMaximumSize(new java.awt.Dimension(180, 40));
        changeToTripButton.setMinimumSize(new java.awt.Dimension(180, 40));
        changeToTripButton.setPreferredSize(new java.awt.Dimension(180, 40));
        changeToTripButton.addActionListener(this::changeToTripButtonActionPerformed);
        buttonPanel.add(changeToTripButton);

        getTicketsOfUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTicketsOfUserButton.setText("Get Tickets Of User");
        getTicketsOfUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTicketsOfUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.addActionListener(this::getTicketsOfUserButtonActionPerformed);
        buttonPanel.add(getTicketsOfUserButton);

        deleteTicketButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteTicketButton.setText("Delete Ticket");
        deleteTicketButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteTicketButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteTicketButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteTicketButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteTicketButton.addActionListener(this::deleteTicketButtonActionPerformed);
        buttonPanel.add(deleteTicketButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("TICKETS");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getTicketsOfUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTicketsOfUserButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter UserID to list tickets:",
                "Tickets Of User", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "UserID required.", "Input",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int userId;
        try {
            userId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid UserID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            middlePanel.setTableContents(resultTable, ticketQuery.getTicketsOfUser(userId));
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching tickets: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_getTicketsOfUserButtonActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed

    }//GEN-LAST:event_buyTicketButtonActionPerformed

    private void myTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myTicketsButtonActionPerformed
        middlePanel.setTableContents(resultTable, ticketQuery.getTicketsOfUser(userLoginSession.getUserId()));
    }//GEN-LAST:event_myTicketsButtonActionPerformed

    private void changeToTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeToTripButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeToTripButtonActionPerformed

    private void deleteTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTicketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTicketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JButton changeToTripButton;
    private javax.swing.JButton deleteTicketButton;
    private javax.swing.JButton getTicketsOfUserButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton myTicketsButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        changeToTripButton.setVisible(false);
        deleteTicketButton.setVisible(false);
        getTicketsOfUserButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        changeToTripButton.setVisible(true);
        deleteTicketButton.setVisible(true);
        getTicketsOfUserButton.setVisible(true);
    }
}
