/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;

import com.buspass.gui.app_gui.dialogs.TripCreatePanel;
import com.buspass.gui.app_gui.dialogs.TripUpdatePanel;
import com.buspass.queries.TripQuery;

/**
 *
 * @author USER
 */
public class TripsPanel extends javax.swing.JPanel implements InMiddlePanel {

    /**
     * Creates new form UsersPanel
     */
    public TripsPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private TripQuery tripQuery = new TripQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        upcomingTripsButton = new javax.swing.JButton();
        getTripByIdButton = new javax.swing.JButton();
        getAllTripsButton = new javax.swing.JButton();
        routesAndTripsButton = new javax.swing.JButton();
        joinedQueryButton = new javax.swing.JButton();
        createTripButton = new javax.swing.JButton();
        updateTripButton = new javax.swing.JButton();
        deleteTriprButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        upcomingTripsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        upcomingTripsButton.setText("Upcoming Trips");
        upcomingTripsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        upcomingTripsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        upcomingTripsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        upcomingTripsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        upcomingTripsButton.addActionListener(this::upcomingTripsButtonActionPerformed);
        buttonPanel.add(upcomingTripsButton);

        getTripByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTripByIdButton.setText("Get Trip By ID");
        getTripByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTripByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTripByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTripByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTripByIdButton.addActionListener(this::getTripByIdButtonActionPerformed);
        buttonPanel.add(getTripByIdButton);

        getAllTripsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllTripsButton.setText("Get All Trips");
        getAllTripsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllTripsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllTripsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllTripsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllTripsButton.addActionListener(this::getAllTripsButtonActionPerformed);
        buttonPanel.add(getAllTripsButton);

        routesAndTripsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routesAndTripsButton.setText("Routes and Trips");
        routesAndTripsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routesAndTripsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        routesAndTripsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        routesAndTripsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        routesAndTripsButton.addActionListener(this::routesAndTripsButtonActionPerformed);
        buttonPanel.add(routesAndTripsButton);

        joinedQueryButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        joinedQueryButton.setText("Joined Query");
        joinedQueryButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        joinedQueryButton.setMaximumSize(new java.awt.Dimension(180, 40));
        joinedQueryButton.setMinimumSize(new java.awt.Dimension(180, 40));
        joinedQueryButton.setPreferredSize(new java.awt.Dimension(180, 40));
        joinedQueryButton.addActionListener(this::joinedQueryButtonActionPerformed);
        buttonPanel.add(joinedQueryButton);

        createTripButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createTripButton.setText("Create Trip");
        createTripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createTripButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createTripButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createTripButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createTripButton.addActionListener(this::createTripButtonActionPerformed);
        buttonPanel.add(createTripButton);

        updateTripButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateTripButton.setText("Update Trip");
        updateTripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateTripButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateTripButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateTripButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateTripButton.addActionListener(this::updateTripButtonActionPerformed);
        buttonPanel.add(updateTripButton);

        deleteTriprButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteTriprButton.setText("Delete Trip");
        deleteTriprButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteTriprButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteTriprButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteTriprButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteTriprButton.addActionListener(this::deleteTriprButtonActionPerformed);
        buttonPanel.add(deleteTriprButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("TRIPS");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upcomingTripsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upcomingTripsButtonActionPerformed
        middlePanel.setTableContents(resultTable, tripQuery.getUpcomingTrips());
    }//GEN-LAST:event_upcomingTripsButtonActionPerformed

    private void updateTripButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateTripButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Update Trip",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        TripUpdatePanel panel = new TripUpdatePanel(tripQuery);
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getCreateButton().addActionListener(e -> dialog.dispose());

        dialog.setVisible(true); // blocks until closed
    }// GEN-LAST:event_updateTripButtonActionPerformed

    private void getTripByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getTripByIdButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter TripID:", "Find Trip",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "TripID cannot be empty.", "Input error",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tripId;
        try {
            tripId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric TripID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> trip = tripQuery.getTripById(tripId);
            if (trip == null || trip.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No trip found with ID: " + tripId, "Not found",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }
            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(trip);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching trip: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_getTripByIdButtonActionPerformed

    private void getAllTripsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_getAllTripsButtonActionPerformed
        middlePanel.setTableContents(resultTable, tripQuery.getAllTrips());
    }// GEN-LAST:event_getAllTripsButtonActionPerformed

    private void routesAndTripsButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_routesAndTripsButtonActionPerformed
        try {
            middlePanel.setTableContents(resultTable, tripQuery.getTripsWithJoin());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching routes and trips: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_routesAndTripsButtonActionPerformed

    private void joinedQueryButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_joinedQueryButtonActionPerformed
        try {
            middlePanel.setTableContents(resultTable, tripQuery.getTripsWithJoinAndDrivers());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching joined query: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_joinedQueryButtonActionPerformed

    private void createTripButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createTripButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Create Trip",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        TripCreatePanel panel = new TripCreatePanel(tripQuery);
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getCreateButton().addActionListener(e -> dialog.dispose());

        dialog.setVisible(true); // blocks until closed
    }// GEN-LAST:event_createTripButtonActionPerformed

    private void deleteTriprButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteTriprButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter TripID to delete:", "Delete Trip",
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null)
            return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "TripID required.", "Input",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int tripId;
        try {
            tripId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid TripID.", "Input error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete TripID " + tripId + "?", "Confirm",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION)
            return;
        try {
            boolean ok = tripQuery.removeTrip(tripId);
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "Trip deleted.", "Success",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                middlePanel.setTableContents(resultTable, tripQuery.getAllTrips());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Trip not found or failed to delete.", "Failure",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting trip: " + ex.getMessage(), "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }// GEN-LAST:event_deleteTriprButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createTripButton;
    private javax.swing.JButton deleteTriprButton;
    private javax.swing.JButton getAllTripsButton;
    private javax.swing.JButton getTripByIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton joinedQueryButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton routesAndTripsButton;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton upcomingTripsButton;
    private javax.swing.JButton updateTripButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        getAllTripsButton.setVisible(false);
        createTripButton.setVisible(false);
        updateTripButton.setVisible(false);
        deleteTriprButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        getAllTripsButton.setVisible(true);
        createTripButton.setVisible(true);
        updateTripButton.setVisible(true);
        deleteTriprButton.setVisible(true);
    }
}
