/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.middle_panels;


import java.util.Map;

import javax.swing.JOptionPane;

import com.buspass.gui.app_gui.dialogs.UserCreatePanel;
import com.buspass.gui.app_gui.dialogs.UserUpdatePanel;
import com.buspass.queries.UserService;
import com.buspass.utils.*;

/**
 *
 * @author USER
 */
public class UsersPanel extends javax.swing.JPanel implements InMiddlePanel{

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private UserService userService = new UserService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getUserByIdButton = new javax.swing.JButton();
        getAllUsersButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        findIdButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getUserByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getUserByIdButton.setText("Get User By ID");
        getUserByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getUserByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.addActionListener(this::getUserByIdButtonActionPerformed);
        buttonPanel.add(getUserByIdButton);

        getAllUsersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllUsersButton.setText("Get All Users");
        getAllUsersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllUsersButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.addActionListener(this::getAllUsersButtonActionPerformed);
        buttonPanel.add(getAllUsersButton);

        createUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createUserButton.addActionListener(this::createUserButtonActionPerformed);
        buttonPanel.add(createUserButton);

        updateUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateUserButton.setText("Update User");
        updateUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateUserButton.addActionListener(this::updateUserButtonActionPerformed);
        buttonPanel.add(updateUserButton);

        findIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findIdButton.setText("Find UserID By Username");
        findIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        findIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        findIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        findIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        findIdButton.addActionListener(this::findIdButtonActionPerformed);
        buttonPanel.add(findIdButton);

        deleteUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteUserButton.setText("Delete User");
        deleteUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteUserButton.addActionListener(this::deleteUserButtonActionPerformed);
        buttonPanel.add(deleteUserButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.CardLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("USERS");
        headerPanel.add(headerLabel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Create User", java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        UserUpdatePanel panel = new UserUpdatePanel(userService);
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getUpdateButton().addActionListener(e -> {
            int userId = panel.retrieveUserId();
            if (userId <= 0) return;

            String username = panel.getUsername();
            String password = panel.getPassword();
            String fullName = panel.getFullName();
            String phone = panel.getPhone();
            String address = panel.getAddress();


            if (!AuthUtils.isValidUsername(username)) { DialogUtils.showDialogInvalidUsername(); return; }
            if (!password.isEmpty() && !AuthUtils.isValidPassword(password)) { DialogUtils.showDialogInvalidPWs(); return; }

            int age = 0; // default
            try { age = panel.getAge(); } catch (Exception exNum) { JOptionPane.showMessageDialog(panel, "Age must be an integer.", "Validation", JOptionPane.WARNING_MESSAGE); return; }
            int roleId = 1; // default passenger
            try { roleId = panel.getUserRoleId(); } catch (Exception exNum) { JOptionPane.showMessageDialog(panel, "UserRoleID must be an integer.", "Validation", JOptionPane.WARNING_MESSAGE); return; }

            try {
                boolean ok = true;
                
                // Username Validation
                if (ok) { 
                    int result = userService.updateUsername(userId, username);
                    if (result == 0) {
                        DialogUtils.showDialogUserAlreadyExists(username);
                        return;
                    }
                }
                // Check if password update is necessary
                if (ok && !password.isEmpty())
                    ok = userService.updatePassword(userId, password);

                if (ok) ok = userService.updateFullName(userId, fullName);
                if (ok) ok = userService.updateAge(userId, age);
                if (ok) ok = userService.updatePhoneNumber(userId, phone);
                if (ok) ok = userService.updateAddress(userId, address);
                if (ok) ok = userService.updateRoleID(userId, roleId);

                if (ok) {
                    JOptionPane.showMessageDialog(panel, "User Update success.", "Updated", JOptionPane.INFORMATION_MESSAGE);
                    dialog.dispose();
                    middlePanel.setTableContents(resultTable, userService.getAllUsers());
                } else {
                    JOptionPane.showMessageDialog(panel, "User could not be created (no rows affected).", "Failure", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panel, "SQL Error: " + ex.getClass().getSimpleName() + ": " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        dialog.setVisible(true); // blocks until closed
    }//GEN-LAST:event_updateUserButtonActionPerformed

    private void getUserByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUserByIdButtonActionPerformed
        // Super temporary solution for retriving User

        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter UserID:", "Find User", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return; // user cancelled
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "UserID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int userId;
        try {
            userId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric UserID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Map<String, Object> user = userService.getUserById(userId);
            if (user == null || user.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No user found with ID: " + userId, "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }

            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(user);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching user: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_getUserByIdButtonActionPerformed

    private void getAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllUsersButtonActionPerformed
        middlePanel.setTableContents(resultTable, userService.getAllUsers());
    }//GEN-LAST:event_getAllUsersButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // Open modal dialog with UserCreatePanel; only close on CANCEL or closing the Window
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Create User", java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        UserCreatePanel panel = new UserCreatePanel();
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getCreateButton().addActionListener(e -> {
            String username = panel.getUsername();
            String password = panel.getPassword();
            String fullName = panel.getFullName();
            String phone = panel.getPhone();
            String address = panel.getAddress();

            if (!AuthUtils.isValidUsername(username)) { DialogUtils.showDialogInvalidUsername(); return; }
            if (!AuthUtils.isValidPassword(password)) { DialogUtils.showDialogInvalidPWs(); return; }

            int age = 0; // default
            try { age = panel.getAge(); } catch (Exception exNum) { JOptionPane.showMessageDialog(panel, "Age must be an integer.", "Validation", JOptionPane.WARNING_MESSAGE); return; }
            int roleId = 1; // default passenger
            try { roleId = panel.getUserRoleId(); } catch (Exception exNum) { JOptionPane.showMessageDialog(panel, "UserRoleID must be an integer.", "Validation", JOptionPane.WARNING_MESSAGE); return; }

            try {
                boolean ok = userService.registerUserDetailed(username, password, fullName, age, phone, address, roleId);
                if (ok) {
                    DialogUtils.showDialogRegistrationSuccess(username);
                    dialog.dispose();
                    middlePanel.setTableContents(resultTable, userService.getAllUsers());
                } else {
                    JOptionPane.showMessageDialog(panel, "User could not be created (no rows affected).", "Failure", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(panel, "SQL Error: " + ex.getClass().getSimpleName() + ": " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        });
        dialog.setVisible(true); // blocks until closed
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        String username = javax.swing.JOptionPane.showInputDialog(this, "Enter username to find UserID:", "Find UserID", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (username == null) return;
        username = username.trim();
        if (username.isEmpty()) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Username cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int id = userService.getIdByUsername(username);
            if (id <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "User not found.", "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "UserID for '" + username + "' is: " + id, "Found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error finding user: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            // ex.printStackTrace();
        }
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter UserID to delete:", "Delete User", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "UserID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        int userId;
        try {
            userId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric UserID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete UserID " + userId + "?", "Confirm delete", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
        try {
            boolean ok = userService.deleteUserById(userId);
            if (ok) {
                javax.swing.JOptionPane.showMessageDialog(this, "User deleted.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                middlePanel.setTableContents(resultTable, userService.getAllUsers());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "User not found or could not be deleted.", "Failure", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting user: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_deleteUserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton findIdButton;
    private javax.swing.JButton getAllUsersButton;
    private javax.swing.JButton getUserByIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateUserButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void hideAdminButtons() {
        createUserButton.setVisible(false);
        deleteUserButton.setVisible(false);
        findIdButton.setVisible(false);
        getAllUsersButton.setVisible(false);
        getUserByIdButton.setVisible(false);
        updateUserButton.setVisible(false);
    }

    @Override
    public void showAdminButtons() {
        createUserButton.setVisible(true);
        deleteUserButton.setVisible(true);
        findIdButton.setVisible(true);
        getAllUsersButton.setVisible(true);
        getUserByIdButton.setVisible(true);
        updateUserButton.setVisible(true);
    }
}
